services:
  mysql-nodo3:
    image: mysql:8.4
    container_name: mysql-nodo3
    restart: unless-stopped
    hostname: mysql-nodo3
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: data_bugs
    ports:
      - "3306:3306"   
      - "33061:33061"  
    volumes:
      - ./conf/my.cnf:/tmp/nodo3.cnf:ro
      - datos_nodo3:/var/lib/mysql
    entrypoint:
      - bash
      - -c
      - |
        cp /tmp/nodo3.cnf /etc/mysql/conf.d/nodo3.cnf
        chmod 644 /etc/mysql/conf.d/nodo3.cnf
        exec docker-entrypoint.sh mysqld
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 12
    networks:
      red_tailscale:
        ipv4_address: 100.107.61.57

volumes:
  datos_nodo3:

networks:
  red_tailscale:
    driver: bridge
    ipam:
      config:
        - subnet: 100.107.61.0/24
